-- MySQL Script generated by MySQL Workbench
-- 02/07/16 13:07:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chatserver
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chatserver
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chatserver` DEFAULT CHARACTER SET utf8 ;
USE `chatserver` ;

-- -----------------------------------------------------
-- Table `chatserver`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chatserver`.`user` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` CHAR(64) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `first_name` VARCHAR(255) NOT NULL,
  `last_name` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `profile_pic` MEDIUMBLOB NULL,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`email`),
  UNIQUE INDEX `userid_UNIQUE` (`userid` ASC));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
